logging:
  level:
    org:
      springframework: DEBUG
spring:
  application:
    name: spring-ai-alibaba-graph-studio
  config:
    import: classpath:initializr.yml
  ai:
    dashscope:
      api-key: sk-6b76c9f5936a4a5d8facb6daa5cd3b58
server:
  port: 8080
